### ISSUE TITLE
Cannot install latest releases using pip

### ISSUE THREAD

**Issue by guillaume-chech** [quizlet/abracadabra#11]
Hi  thanks for fixing the couple of opened issues it will save the day ! 

Following [issue](https://github.com/quizlet/abracadabra/issues/9) I tried starting from a fresh install running `pip install abracadabra==0.0.5 ` upgrading pip to the latest version as a prerequisite. However it seems pip cannot find the latests realease ( I tried for all version starting from 0.0.2) . 
So I tried running `pip search abracadabra` which returns `abracadabra (0.0.5)  - Making hypothesis and AB testing magically simple!` which is a good sign. 
So I tried again `pip install abracadabra==0.0.5 -vvv` to get a traceback. It looks like the version are not properly named as they are prefixed with the os you're seems to be using. 
See : 
`Fetching project page and analyzing links: https://pypi.org/simple/abracadabra/
Getting page https://pypi.org/simple/abracadabra/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/abracadabra/ HTTP/1.1" 200 987
  Found link https://files.pythonhosted.org/packages/66/71/08dc217003fbdca1e41f51c6cf4552eeb2de8302dd57ac04ad0385d5ca97/abracadabra-0.0.0-py3-none-any.whl#sha256=4030febb5e8ef77167edbd3278b67b926aa8d0db99fb9e40de9f9a2b9766fc8a (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.0
  Found link https://files.pythonhosted.org/packages/07/87/e5d110901f799331f7a44ff3c21c2415f24ba7b5cefa11d82eda6a95e62e/abracadabra-0.0.0.tar.gz#sha256=5eeed338934a3dee3f4ee004b8143ea38e0ef1fc89d20eec156e8f5bcae9bd12 (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.0
  Found link https://files.pythonhosted.org/packages/9b/01/d220895a4c4dc1c1e5cb03268186386db9e6be0f8899e98c5e4af3075551/abracadabra-0.0.1-py3-none-any.whl#sha256=b7419a9979a7e40ad741c7106da390d91793702fc25934ac433095dbaf613fa3 (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.1
  Found link https://files.pythonhosted.org/packages/be/1d/0260508bfb3cd5df77645e8f31a5239c7f91328e79711e35c72a1a401f80/abracadabra-0.0.1.tar.gz#sha256=934b6b4eae2464617de5edc9520d7433602f3bb3b5d3c66dd0d2a9116e35a2d4 (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.1
  Found link https://files.pythonhosted.org/packages/e0/2b/10b48197772fa2258769e4bb380e020ab9a253d4be091d91cad6a1eadd13/abracadabra-0.0.2.macosx-10.14-x86_64.tar.gz#sha256=3a27f22f64f7d18663723dae5abd8ec32d469720fd45ffa68293faa6199e19b6 (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.2.macosx-10.14-x86_64
  Found link https://files.pythonhosted.org/packages/80/de/4c0a62d459466926f1ca550c22669a3eb968c94903854c0c045bb5720706/abracadabra-0.0.3.macosx-10.14-x86_64.tar.gz#sha256=073866a99037bcbd8a32f48c511957b0b67b6ffb4b16c6bfd40b06d43681a7ce (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.3.macosx-10.14-x86_64
  Found link https://files.pythonhosted.org/packages/dd/84/993353040d5549de039597b00aafc9fd0681ee99e3077a96996d53cffdaa/abracadabra-0.0.4.macosx-10.14-x86_64.tar.gz#sha256=27e69fcf368d7b2b835c784887b1b34a318d7b2f3340e3d826141cffcc4fd71f (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.4.macosx-10.14-x86_64
  Found link https://files.pythonhosted.org/packages/7b/8a/aab62563ebbbd014c3e80dc4c3cfd2b9491d28e2835f969405092ee5bd1d/abracadabra-0.0.5.macosx-10.14-x86_64.tar.gz#sha256=424aa28d3f5d7bdc26129f4e6e18764be07fb75f425a5762176575a1f6ed62b4 (from https://pypi.org/simple/abracadabra/) (requires-python:>=3.7), version: 0.0.5.macosx-10.14-x86_64
Given no hashes to check 0 links for project 'abracadabra': discarding no candidates
ERROR: Could not find a version that satisfies the requirement abracadabra==0.0.5
ERROR: No matching distribution found for abracadabra==0.0.5`

So I finally tried `pip install abracadabra==0.0.5.macosx-10.14-x86_64` which fixes the issue and install the latest release. I think this is kinda unintuitive, I advise you maybe change the versions indexes .

**Comment by dustinstansbury** [comment]
Sorry about that @guillaume-chech . The wheel install for 0.0.5 is now available. I've verified that

```bash
$ pipenv install abracadabra==0.0.5
```
 installs as expected on fresh virtualenv.
