### ISSUE TITLE
Unknown inference method 'bootstrap'

### ISSUE THREAD

**Issue by JieFang830** [quizlet/abracadabra#7]
Hi there,
Thanks for building this amazing A/B testing tool. I was playing around with it but I got some errors. I was copy-pasting the exact same code from the tutorial. 
Please advise:
![image](https://user-images.githubusercontent.com/26362386/97226152-d5862580-1790-11eb-9229-70e1a8e5e780.png)

Also, I failed in pip install -U abracadabra, now I am using abracadabra==0.0.1.
Thank you!

**Comment by dustinstansbury** [comment]
The current [version on PyPi is 0.0.4](https://pypi.org/project/abracadabra/). Not sure why the upgrade failed, but a successful upgrade _should_ solve the issue.

**Comment by dustinstansbury** [comment]
I've just verified with a fresh install. `BootstrapDelta` part of the docs appears to work fine.
