### ISSUE TITLE
Documentation and current version not in sync

### ISSUE THREAD

**Issue by guillaume-chech** [quizlet/abracadabra#9]
Hi guys ! Thanks a lot for the wonderful tool you built here and for the real good documentation associated. 
In the documentation you showcase inference method like 'bootstrap' or 'exp_student-t'  that are not yet usable for some reason. My feeling is that current pip version (0.0.1) is not up to date with the state of documentation and is missleading. 

Do you think you guys could release more up to date versions ?

**Comment by dustinstansbury** [comment]
Hi! Thanks, glad you're enjoying abracadabra.

The current version [on PiPy is 0.0.4](https://pypi.org/project/abracadabra/) (it has been 0.0.3 for a few months now). Try upgrading and see if that helps alleviate the issue.

**Comment by dustinstansbury** [comment]
I've just verified with a fresh install. `BootstrapDelta` part of the docs appears to work fine.

**Comment by dustinstansbury** [comment]
I'll have to dig into the student-t. Could be a bug in the docs.

**Comment by dustinstansbury** [comment]
Looks like the `student_t` and `exp_student_t` models, though available from the low-level API, weren't added as options to the top-level `HypothesisTest` API. Version 0.0.5 is out now, which addresses the issue.

**Comment by guillaume-chech** [comment]
Thank you for fixing that !
